using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;
using WordAI.Agent.Protocol;
using WordAI.Agent.Word;

namespace WordAI.Agent.Gateway
{
    /// <summary>
    /// Word 本地网关服务器：监听 127.0.0.1（仅回环），JSON Lines 协议（见 docs/protocol-b.md）。
    ///
    /// 关键设计：
    /// - 会话认证：连接后首条消息必须是 auth；未认证调用返回 -32001，连续 3 次断开
    /// - Word COM 单线程约束：所有 word.* 请求经串行队列执行，天然规避 COM 并发异常
    /// - 取消语义（三段式）：超时由客户端自行放弃等待；cancel 通知对「尚未开始」跳过、
    ///   对「可协作取消」置 CancellationToken、对「不可中断 COM 调用」等其执行完丢弃结果
    /// - deadline：信封携带 deadlineMs，完成时超期则回 -32004
    /// - 单行长度上限：超过即回 -32002 并断开连接
    /// </summary>
    public sealed class WordGatewayServer : IDisposable
    {
        private readonly IWordHost _host;
        private readonly string _token;
        private readonly string _serverVersion;
        private readonly int _maxLineChars;
        private readonly Action<string> _log;
        private readonly int _port;

        /// <summary>协议输出统一 camelCase（与 docs/protocol-b.md 字段名约定一致）。</summary>
        private static readonly Newtonsoft.Json.JsonSerializer CamelJson =
            new Newtonsoft.Json.JsonSerializer
            {
                ContractResolver = new Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver()
            };

        private TcpListener _listener;
        private readonly CancellationTokenSource _shutdownCts = new CancellationTokenSource();
        private readonly SemaphoreSlim _comLock = new SemaphoreSlim(1, 1); // Word COM 串行队列
        private readonly ConcurrentDictionary<string, CancellationTokenSource> _inFlight =
            new ConcurrentDictionary<string, CancellationTokenSource>();
        private int _nextConnId;

        private WordGatewayServer(int port, string token, IWordHost host, string serverVersion, int maxLineChars, Action<string> log)
        {
            _port = port;
            _token = token;
            _host = host;
            _serverVersion = serverVersion;
            _maxLineChars = maxLineChars;
            _log = log ?? (_ => { });
        }

        /// <summary>启动网关。token 由调用方生成（通常经环境变量注入 Pi 子进程由扩展携带）。</summary>
        public static WordGatewayServer Start(int port, string token, IWordHost host,
            string serverVersion = null, int? maxLineChars = null, Action<string> log = null)
        {
            if (port <= 0) throw new ArgumentOutOfRangeException(nameof(port));
            if (string.IsNullOrEmpty(token)) throw new ArgumentException("token must be generated by caller", nameof(token));
            if (host == null) throw new ArgumentNullException(nameof(host));

            int limit = maxLineChars ?? ResolveMaxLine();
            var server = new WordGatewayServer(port, token, host,
                serverVersion ?? ("wordai-agent/" + typeof(WordGatewayServer).Assembly.GetName().Version), limit, log);

            server._listener = new TcpListener(IPAddress.Loopback, port);
            server._listener.Server.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
            server._listener.Start(8);
            server._log($"[gateway] listening on 127.0.0.1:{port} (maxLine={limit})");
            _ = server.AcceptLoopAsync();
            return server;
        }

        private static int ResolveMaxLine()
        {
            var env = Environment.GetEnvironmentVariable(ProtocolConstants.MaxLineEnvVar);
            int v;
            return int.TryParse(env, out v) && v > 0 ? v : ProtocolConstants.DefaultMaxLineBytes;
        }

        private async Task AcceptLoopAsync()
        {
            var ct = _shutdownCts.Token;
            while (!ct.IsCancellationRequested)
            {
                TcpClient client;
                try { client = await _listener.AcceptTcpClientAsync().ConfigureAwait(false); }
                catch (ObjectDisposedException) { break; }
                catch (SocketException) { break; }
                catch (Exception ex)
                {
                    _log($"[gateway] accept loop fatal: {ex.GetType().Name}: {ex.Message}");
                    break;
                }
                if (ct.IsCancellationRequested) { TryClose(client); break; }
                _ = HandleConnectionAsync(client, Interlocked.Increment(ref _nextConnId));
            }
        }

        private sealed class ConnState
        {
            public TcpClient Client;
            public NetworkStream Stream;
            public readonly SemaphoreSlim WriteLock = new SemaphoreSlim(1, 1);
            public bool Authenticated;
            public int UnauthAttempts;
            public string SessionId;
            public string ClientVersion;
            public readonly HashSet<string> DiscardIds = new HashSet<string>(); // 已请求取消 → 完成后丢弃
        }

        private async Task HandleConnectionAsync(TcpClient client, int connId)
        {
            var cs = new ConnState { Client = client, Stream = client.GetStream() };
            var decoder = new LineDecoder(_maxLineChars, _log);
            var buf = new byte[16 * 1024];
            var close = false;
            _log($"[gateway] conn#{connId} open");

            try
            {
                while (!close && !_shutdownCts.IsCancellationRequested)
                {
                    int n = await cs.Stream.ReadAsync(buf, 0, buf.Length, _shutdownCts.Token).ConfigureAwait(false);
                    if (n <= 0) break;

                    List<string> lines;
                    try { lines = new List<string>(decoder.Append(buf, n)); }
                    catch (LineDecoder.LineTooLongException)
                    {
                        await WriteResponseAsync(cs, new GatewayResponse { Error = GatewayError.TooLong() });
                        break; // 超长 → 回 -32002 后断开
                    }

                    foreach (var line in lines)
                    {
                        if (string.IsNullOrWhiteSpace(line)) continue;
                        var disposition = await HandleLineAsync(cs, connId, line).ConfigureAwait(false);
                        if (disposition == LineDisposition.Close) { close = true; break; }
                    }
                }
            }
            catch (Exception ex)
            {
                _log($"[gateway] conn#{connId} error: {ex.Message}");
            }
            finally
            {
                TryClose(client);
                _log($"[gateway] conn#{connId} closed");
            }
        }

        private enum LineDisposition { Continue, Close }

        private async Task<LineDisposition> HandleLineAsync(ConnState cs, int connId, string line)
        {
            GatewayRequest req;
            GatewayError parseErr;
            if (!GatewayRequest.TryParse(line, out req, out parseErr))
            {
                await WriteResponseAsync(cs, new GatewayResponse { Error = parseErr }).ConfigureAwait(false);
                return LineDisposition.Continue;
            }

            // ---- 会话认证（连接后首条消息必须是 auth）----
            if (!cs.Authenticated)
            {
                if (req.Method != "auth")
                {
                    cs.UnauthAttempts++;
                    await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Error = GatewayError.AuthFailed() });
                    if (cs.UnauthAttempts >= ProtocolConstants.MaxUnauthAttempts)
                    {
                        _log($"[gateway] conn#{connId} closed after {cs.UnauthAttempts} unauthenticated attempts");
                        return LineDisposition.Close;
                    }
                    return LineDisposition.Continue;
                }

                var authErr = await HandleAuthAsync(cs, connId, req).ConfigureAwait(false);
                if (authErr != null)
                {
                    await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Error = authErr }).ConfigureAwait(false);
                    if (authErr.Code == GatewayErrorCodes.VersionMismatch) return LineDisposition.Close;
                    cs.UnauthAttempts++;
                    return LineDisposition.Continue;
                }
                return LineDisposition.Continue;
            }

            // ---- cancel 通知：尽力取消（三段语义），不阻塞读循环 ----
            if (req.Method == "cancel")
            {
                HandleCancel(cs, connId, req);
                return LineDisposition.Continue; // 通知无响应
            }

            // ---- 业务请求：异步分发，读循环继续收消息（cancel 才能插进来）----
            _ = DispatchAsync(cs, connId, req);
            return LineDisposition.Continue;
        }

        private async Task<GatewayError> HandleAuthAsync(ConnState cs, int connId, GatewayRequest req)
        {
            var p = req.Params ?? new JObject();
            int clientVersion = p.Value<int?>("protocolVersion") ?? 0;
            if (clientVersion != ProtocolConstants.ProtocolVersion)
            {
                _log($"[gateway] conn#{connId} auth rejected: protocol version {clientVersion} != {ProtocolConstants.ProtocolVersion}");
                return GatewayError.VersionMismatch(clientVersion, ProtocolConstants.ProtocolVersion);
            }

            var token = p.Value<string>("token");
            if (!string.Equals(token, _token, StringComparison.Ordinal))
            {
                _log($"[gateway] conn#{connId} auth rejected: invalid token");
                return new GatewayError(GatewayErrorCodes.AuthFailed, "invalid token");
            }

            cs.Authenticated = true;
            cs.SessionId = Guid.NewGuid().ToString("D");
            cs.ClientVersion = p.Value<string>("clientVersion") ?? "unknown";

            var result = new JObject
            {
                ["authed"] = true,
                ["sessionId"] = cs.SessionId,
                ["protocolVersion"] = ProtocolConstants.ProtocolVersion,
                ["serverVersion"] = _serverVersion,
                ["clientVersion"] = cs.ClientVersion,
                ["capabilities"] = new JArray(ProtocolConstants.Capabilities)
            };
            await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Result = result }).ConfigureAwait(false);
            _log($"[gateway] conn#{connId} session established (client={cs.ClientVersion}, session={cs.SessionId})");
            return null;
        }

        private void HandleCancel(ConnState cs, int connId, GatewayRequest req)
        {
            var targetId = (req.Params ?? new JObject()).Value<string>("id");
            if (string.IsNullOrEmpty(targetId)) return;

            CancellationTokenSource cts;
            if (_inFlight.TryGetValue(targetId, out cts))
            {
                // 已在执行：协作取消（interruptible 任务响应 token；不可中断任务不受影响，执行完丢弃）
                try { cts.Cancel(); } catch (ObjectDisposedException) { }
                cs.DiscardIds.Add(targetId);
                _log($"[gateway] conn#{connId} cancel requested for in-flight {targetId}");
            }
            else
            {
                cs.DiscardIds.Add(targetId); // 尚未开始 / 未知 id：标记丢弃
                _log($"[gateway] conn#{connId} cancel accepted for {targetId} (not started/unknown)");
            }
        }

        private async Task DispatchAsync(ConnState cs, int connId, GatewayRequest req)
        {
            if (req.Version != ProtocolConstants.ProtocolVersion)
            {
                await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Error = GatewayError.VersionMismatch(req.Version, ProtocolConstants.ProtocolVersion) });
                return;
            }

            var sw = Stopwatch.StartNew();
            var needsCom = req.Method.StartsWith("word.", StringComparison.Ordinal);
            var cts = new CancellationTokenSource();
            if (!_inFlight.TryAdd(req.Id, cts))
            {
                await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Error = GatewayError.Internal("duplicate request id") });
                return;
            }

            try
            {
                if (needsCom)
                {
                    // 尚未开始即已取消 → 跳过执行、不回包
                    if (cs.DiscardIds.Contains(req.Id))
                    {
                        _log($"[gateway] conn#{connId} {req.Id} skipped (cancelled before start)");
                        return;
                    }

                    // 锁获取保持同步（沿 JSONL 行序排队，保证 word.* 执行顺序）；
                    // 宿主调用放进线程池执行，读循环不被 COM 阻塞，cancel 才能在执行期间到达
                    await _comLock.WaitAsync(cts.Token).ConfigureAwait(false); // Word COM 串行队列
                    try
                    {
                        if (cs.DiscardIds.Contains(req.Id) || cts.IsCancellationRequested)
                        {
                            _log($"[gateway] conn#{connId} {req.Id} skipped (cancelled while queued)");
                            return;
                        }
                        var result = await Task.Run(() => ExecuteWordMethodAsync(req, cts.Token)).ConfigureAwait(false);

                        // 取消语义收口：不可中断操作执行完 → 结果丢弃
                        if (cs.DiscardIds.Remove(req.Id))
                        {
                            _log($"[gateway] conn#{connId} late response discarded (cancelled, id={req.Id})");
                            return;
                        }

                        // deadline 超期：回 -32004（客户端可能已不再等待，按协议丢弃迟到回包）
                        if (req.DeadlineMs.HasValue && sw.ElapsedMilliseconds > req.DeadlineMs.Value)
                        {
                            _log($"[gateway] conn#{connId} {req.Id} deadline exceeded ({sw.ElapsedMilliseconds}ms > {req.DeadlineMs}ms)");
                            await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Error = GatewayError.Deadline() });
                            return;
                        }

                        await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Result = JToken.Parse(result) });
                    }
                    finally { _comLock.Release(); }
                }
                else
                {
                    var result = await Task.Run(() => ExecuteSessionMethodAsync(req, cs)).ConfigureAwait(false);
                    if (cs.DiscardIds.Remove(req.Id))
                    {
                        _log($"[gateway] conn#{connId} late response discarded (cancelled, id={req.Id})");
                        return;
                    }
                    // deadline 同样适用于非 COM 方法（如测试方法 session.slowEcho）
                    if (req.DeadlineMs.HasValue && sw.ElapsedMilliseconds > req.DeadlineMs.Value)
                    {
                        _log($"[gateway] conn#{connId} {req.Id} deadline exceeded ({sw.ElapsedMilliseconds}ms > {req.DeadlineMs}ms)");
                        await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Error = GatewayError.Deadline() });
                        return;
                    }
                    await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Result = JToken.Parse(result) });
                }
            }
            catch (OperationCanceledException)
            {
                _log($"[gateway] conn#{connId} {req.Id} cancelled during execution (cooperative)");
            }
            catch (MethodNotFoundEx ex)
            {
                await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Error = GatewayError.MethodNotFound(ex.Message) });
            }
            catch (Exception ex)
            {
                if (!cs.DiscardIds.Remove(req.Id))
                    await WriteResponseAsync(cs, new GatewayResponse { Id = req.Id, Error = GatewayError.Internal(ex.Message) });
                else
                    _log($"[gateway] conn#{connId} {req.Id} failed after cancel, response discarded");
            }
            finally
            {
                CancellationTokenSource removed;
                _inFlight.TryRemove(req.Id, out removed);
                cts.Dispose();
            }
        }

        private Task<string> ExecuteWordMethodAsync(GatewayRequest req, CancellationToken ct)
        {
            var p = req.Params ?? new JObject();
            switch (req.Method)
            {
                case "word.getDocumentInfo":
                    return Safe(JObject.FromObject(_host.GetDocumentInfo(), CamelJson));
                case "word.insertText":
                {
                    var text = p.Value<string>("text") ?? "";
                    InsertPosition pos;
                    switch ((p.Value<string>("position") ?? "selection").ToLowerInvariant())
                    {
                        case "documentend": case "document-end": pos = Word.InsertPosition.DocumentEnd; break;
                        case "documentstart": case "document-start": pos = Word.InsertPosition.DocumentStart; break;
                        default: pos = Word.InsertPosition.Selection; break;
                    }
                    return Safe(JObject.FromObject(_host.InsertText(text, pos), CamelJson));
                }
                case "word.getSelection":
                    return Safe(JObject.FromObject(_host.GetSelection(), CamelJson));
                case "word.find":
                {
                    var query = p.Value<string>("query") ?? "";
                    int maxHits = p.Value<int?>("maxHits") ?? 50;
                    return Safe(JObject.FromObject(_host.Find(query, maxHits, ct), CamelJson));
                }
                case "word.replace":
                {
                    var find = p.Value<string>("find") ?? "";
                    var rep = p.Value<string>("replace") ?? "";
                    bool all = p.Value<bool?>("all") ?? true;
                    return Safe(JObject.FromObject(_host.Replace(find, rep, all, ct), CamelJson));
                }
                case "word.applyStyle":
                {
                    var style = p.Value<string>("paragraphStyle") ?? "";
                    bool apply = p.Value<bool?>("apply") ?? true;
                    return Safe(JObject.FromObject(_host.ApplyStyle(style, apply, ct), CamelJson));
                }
                case "word.save":
                    _host.Save();
                    return Safe(new JObject { ["saved"] = true });
                default:
                    throw new MethodNotFoundEx(req.Method);
            }
        }

        private sealed class MethodNotFoundEx : Exception
        {
            public MethodNotFoundEx(string m) : base(m) { }
        }

        private Task<string> ExecuteSessionMethodAsync(GatewayRequest req, ConnState cs)
        {
            var p = req.Params ?? new JObject();
            switch (req.Method)
            {
                case "session.echo":
                {
                    var o = new JObject { ["echoed"] = true };
                    foreach (var kv in p) if (kv.Key != "deadlineMs") o[kv.Key] = kv.Value;
                    return Safe(o);
                }
                case "session.slowEcho":
                {
                    // 模拟不可中断 COM 调用：delayMs 毫秒后原样回显（测试专用，不响应 cancel）
                    int delayMs = Math.Min(p.Value<int?>("delayMs") ?? 100, 60000);
                    return Task.Run(async () =>
                    {
                        await Task.Delay(delayMs);
                        var o = new JObject { ["echoed"] = true, ["delayMs"] = delayMs };
                        foreach (var kv in p)
                            if (kv.Key != "delayMs" && kv.Key != "deadlineMs") o[kv.Key] = kv.Value;
                        return await Safe(o);
                    });
                }
                case "system.info":
                {
                    var o = new JObject
                    {
                        ["serverVersion"] = _serverVersion,
                        ["protocolVersion"] = ProtocolConstants.ProtocolVersion,
                        ["capabilities"] = new JArray(ProtocolConstants.Capabilities),
                        ["sessionId"] = cs.SessionId
                    };
                    return Safe(o);
                }
                default:
                    throw new MethodNotFoundEx(req.Method);
            }
        }

        private static Task<string> Safe(JObject o) { return Task.FromResult(o.ToString(Newtonsoft.Json.Formatting.None)); }

        private async Task WriteResponseAsync(ConnState cs, GatewayResponse resp)
        {
            try
            {
                var line = resp.ToLine();
                var bytes = Encoding.UTF8.GetBytes(line);
                await cs.WriteLock.WaitAsync().ConfigureAwait(false);
                try
                {
                    await cs.Stream.WriteAsync(bytes, 0, bytes.Length).ConfigureAwait(false);
                    await cs.Stream.FlushAsync().ConfigureAwait(false);
                }
                finally { cs.WriteLock.Release(); }
            }
            catch (Exception ex)
            {
                _log($"[gateway] write failed: {ex.Message}");
            }
        }

        private static void TryClose(TcpClient client)
        {
            try { client?.Close(); } catch { }
        }

        public void Dispose()
        {
            _shutdownCts.Cancel();
            try { _listener?.Stop(); } catch { }
            try { _listener?.Server?.Close(); } catch { }
        }
    }
}
